### ISSUE TITLE
TelnetRequestDataTagsEvent

### ISSUE THREAD

**Issue by zD12** [ImALuckyGuy/TatsuCraftFreedomMod#13]
Hi there,
Recently developers have been complaining regarding the BukkitTelnet API's, to be more exact, TelnetRequestDataTagsEvent.  I've recently been playing with the legality of sharing this file, and under the license it states:

"Compiled binaries may be available in the 'Releases' tab of the Github project."
License archive: https://github.com/TotalFreedom/License/commit/03bfff8a00006d46653661129004b534d6ebedc3

Due to this, I may legally upload onto the Github Releases selection, however, limited to purely Github..

Download:
https://github.com/zD12/FreedomOPBukkitTelnet/releases/download/4.2-PRE1/BukkitTelnet.jar

The following version is a prelease version of the official BukkitTelnet.  I've done no modifying, however, I have compiled and uploaded the prelease onto Github (legally).   You may import this version of BukkitTelnet, it has the proper classes so you may compile TatsuCraftFreedomMod.

**Comment by zD12** [comment]
@ImALuckyGuy, mind adding the Label:  "Resolved" and "Download", thanks.

**Comment by RobinGall2910** [comment]
Thanks, I will keep this here for just yeah. links.

**Comment by zD12** [comment]
@RobinGall2910, I don't know why you self-assigned yourself.  I'm just awaiting for @ImALuckyGuy to add the labels.  This applies to all developers.

**Comment by RobinGall2910** [comment]
Ah.
